### ISSUE TITLE
Main Issue

### ISSUE THREAD

**Issue by Yui007** [wandaweb/ComfyUI-Kaggle#1]
Hi. i really like your notebooks i have been using them since i saw your videos on youtube . this isn't my first time making a issue. if u remember i told you about the foocus checkpoint folder issue.

The issue i am facing right now is about ngrok . Ngrok put a limit on their free plan making it only 1gb. Can you find another alternative for this. It will be soooo good if u can do this . i tried to use remotemoe but its not working giving me error it failed to connect. is there any alternative for ngrok please

**Comment by wandaweb** [comment]
Added Zrok and Pinggy support - both are free and don't have limited monthly bandwidth 😊

**Comment by Yui007** [comment]
Thank You so much
